### ISSUE TITLE
investigate heating problem

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/MS5611_SPI#3]
## Problem description

When using the SPI interface of the MS5611 I observe self heating. 
As this sensor seems mostly used by I2C (which is thermal stable) there is little to no information found in the internet on SPI usage and the heating effect found. 
As the measured temperature is used to compensate for the pressure, a faulty temperature results in an incorrect pressure compensation and thus incorrect pressure. 

As I only have one sensor (GY-63) for testing I cannot rule out the sensor or the breakout is broken .

### Observations so far
- library communication works, the values fetched from ROM are identical to I2C. Temperature and pressure are perfect at start (after a disconnected cool down).
- With a 3V3 processor (ESP32) the heat up seems to stabilize around +3-5°C.  (after < 15 minutes)
- With a 5V processor (UNO) the heat up is substantial faster than with a 3V3 device. When temperature was +10°C (1-2 minutes) test stopped to prevent damage.
- the  IN/OUT and CLOCK lines have a current in the uA when not communicating. imho too low to cause heating. 

### Differences with I2C
1. Use of extra pin for communicating from sensor to processor. 
2. Protocol selection pin is connected to GND to select SPI. 
3. SPI select pin, LOW = select, HIGH = not select

Ad 1. driven by the sensor, should not use more pulses == energy compared to I2C output.
Ad 2. The protocol selection pin is pulled up via 1K resistor to 3V3 (I2C as default).  So there is a ~3mA current flowing there => 10mW. As the 3V3 is from a local LDO regulator it should have the same heating effect for VCC = 3V3 or 5V. 
Ad 3. The SPI select pin is pulled down via 1K resistor to GND, So if NOT selected (CS == HIGH) there flows a current that depends on the voltage provided by the processor (?).

**Comment by RobTillaart** [comment]
### Protocol Select pin
platform: ESP32 3V3

#### Connecting the Protocol Selection pin to GND
Measuring current slowly increases from 3.5 uA up (stopped at 4.0 uA). 
Although this is not much I would have expected it to be stable.

#### Connecting the Protocol Selection pin to the SPI SELECT  pin. 
This keeps the line HIGH (I2C mode) when the sensor is not selected.
Effectively it switches for every measurement to SPI mode, communication still works so acceptable.
The current is around 0.50 uA so less than when connecting constantly to GND. 
Self heating continuous although it seems slower.
Putting a 1K resistor between SELECT  and Protocol Selection reduces the current to 0.38uA, the protocol works but self heating still occurs.

So the Protocol Select pin via a 1K to SELECT seems good as the current through PS is minimized.
However it does not solve the self heating.

**Comment by RobTillaart** [comment]
### SPI SELECT pin

platform: ESP32 3V3

#### Controlling SELECT with HIGH LOW

Measuring current starts around 1mA but drops slowly to ~10 uA
Putting a 1K between processor and sensor crashes the readings. 

#### Controlling SELECT with INPUT-OUTPUT

**Comment by RobTillaart** [comment]
### Run for an hour

Stabilizes around 22.56

**Comment by RobTillaart** [comment]
(15-02 by mail from Mario)
- The nr of samples for a temperature reading does not affect the heating 
- I2C non default address also shows heating effect 
_"A: (interesting to note: address 0x76 can NOT be achieved WITHOUT PS connected to HIGH - both cables required)
CSB/SS (I2C address selector) -> 3V3 (HIGH) => 0x76
PS (Protocol select) -> 3V3 (HIGH) => I2C (default)
B: (this is standard configuration, which can also achieved by omitting both cables)
CSB/SS (I2C address selector) -> GND (LOW) => 0x77 (default)
PS (Protocol select) -> 3V3 (HIGH) => I2C (default)
I connected two sensors in order to increase precision and to make it more failsafe.
When powering up I get increasing temp readings of sensor A. I guess, it's due to CSB/SS connected to 3V3."_

**Comment by RobTillaart** [comment]
## Themo Cam

platform: ESP32 3V3 
protocol: SPI

Image made earlier with a (borrowed) thermo cam - with an alignment/shift  problem.
It shows the most heat is in the sensor. (no conclusion can be drawn from that observation)

Need to check if  and how I2C (both addresses) heats up to compare.

![image](https://user-images.githubusercontent.com/462844/154146545-79496ef3-b66d-45a8-9ed6-62922743325c.png)

**Comment by RobTillaart** [comment]
## I2C Test address 0x77

![image](https://user-images.githubusercontent.com/462844/154286311-3aa0278c-7a00-45a1-8fd6-91e681b53f4f.png)

ESP32 - I2C address 0x77  

15:24:49.115 -> T: 20.44 P: 994.64
15:24:50.096 -> T: 20.44 P: 994.64
15:24:51.127 -> T: 20.44 P: 994.54
....
15:31:14.210 -> T: 20.53 P: 994.43
15:31:15.212 -> T: 20.53 P: 994.43
15:31:16.233 -> T: 20.53 P: 994.33

So very little heat up visible in IR and in the readings

**Comment by RobTillaart** [comment]
## I2C Test address 0x76

![image](https://user-images.githubusercontent.com/462844/154287449-def04804-88f6-4f65-a4dc-ee6c814dd741.png)

UNO - I2C address 0x76 

I noticed directly that the LED went brighter when I connected the CS line to +5V
There is also a clear heat increase in the sensor. 
(note the scales are relative compared to previous IR photo)

15:34:54.241 -> T: 22.50 P: 991.75
15:34:55.225 -> T: 22.90 P: 991.87
15:34:56.254 -> T: 23.20 P: 991.95
...
15:35:19.363 -> T: 25.85 P: 991.96
15:35:20.345 -> T: 25.85 P: 991.96
15:35:21.373 -> T: 25.85 P: 991.96

2.5°C increase in ~25 seconds => 0.1°C rise per second  (stopped here)

**Comment by RobTillaart** [comment]
## I2C Test address 0x76  - CS on 3V3
![image](https://user-images.githubusercontent.com/462844/154290139-5fdb64b9-7d9d-4da5-96ab-93401ec577a5.png)

Now I connected the CS line to +3V3

There is also a heat increase in the sensor, but the amount is less than when CS was connected to 5V
roughly about 0.5°C above first measurements.
(note the sensor comes from 25++ C or so and is running for some time now.)

15:38:38.408 -> T: 21.05 P: 994.43
15:38:39.389 -> T: 21.03 P: 994.39
15:38:40.409 -> T: 21.03 P: 994.39
...
15:48:39.732 -> T: 21.07 P: 994.06
15:48:40.713 -> T: 21.07 P: 994.16
15:48:41.742 -> T: 21.07 P: 994.06

**Comment by RobTillaart** [comment]
After a short cool down (no photo)

UNO - I2C address 0x76 

Now I connected the CS line to +3V3   AND device powered by 3V3  (I2C lines are 5V)

15:54:50.134 -> MS5611_LIB_VERSION: 0.3.8
15:54:50.134 -> MS5611 found.
15:54:50.181 ->
15:54:50.181 -> T: 20.70 P: 994.01
15:54:51.165 -> T: 20.70 P: 994.01
15:54:52.149 -> T: 20.72 P: 993.85
...
16:02:07.570 -> T: 20.84 P: 993.72
16:02:08.599 -> T: 20.82 P: 993.68
16:02:09.584 -> T: 20.84 P: 993.72

An increase of 0.1°C which is rather small.

**Comment by RobTillaart** [comment]
Summary

![image](https://user-images.githubusercontent.com/462844/154338398-95e5e65e-100b-4580-be15-bfc0c0ef4e3d.png)

1) my MS5611 is most stable at 3V3 under I2C for address 0x76
2) heat builds up when CS is pulled UP and depends on heavily on voltage
3) heat build up is definitely less than under SPI which I saw stabilizing around +2.5°C

**Comment by RobTillaart** [comment]
https://github.com/RobTillaart/MS5611/pull/17 mentions some early investigations.

**Comment by RobTillaart** [comment]
## Last insights,

The temperature sensor primary function is to compensate the pressure sensor. If we assume it is not meant to be an ambient temperature sensor, self heating (< 5°) should not be a problem as long as it stabilizes. As the sensor itself does not care where the heat comes from, it only needs compensation if temperature is above 20°C.

This assumption solves the self heating problem as it is seen as the solution to obtain normal behavior instead of as an unwanted side effect. 

Note: self heating is a problem when using 5V (see above) and the temperature goes up a lot (not tested how far). 
So a 3V3 recommendation **must** be mentioned in the documentation.

Action to take: update documentation in MS6511 and MS5611_SPI libraries.

**Comment by RobTillaart** [comment]
**multiplexer**
As one user wanted to use 2x MS5611 over I2C it wanted to use address 0x77 and 0x76. As the 0x76 has also some internal heating effect I was asked for a solution. I proposed to use - https://github.com/RobTillaart/TCA9548 - an I2C bus multiplexer.

Today it was confirmed that the multiplexer solution works very well with 2x MS5611 both with address 0x77. 
In such configuration I advice to use two MS5611 objects although technically one could handle both with one.
Some reasons 
- software objects have 1 to 1 relation with real object (easier to understand design)
- per device calibration 
- easier to understand when code addresses which sensor. (less mental load for the coder)

**Comment by nachocpol** [comment]
I'm working on my own library to control the MS5611 and I'm finding similar issues with temperature. I2C seems to be mostly correct (seeing 2.5C+ compared to my smart watch).
SPI is much worse, temp starts going up (reached 30C and I stopped it there).
I feel like this is because I'm using an Arduino NANO, which is 5V, and I don't think this IC supports this kind of voltage. The data sheet does mention that the device supports up to +3.6V so I guess this makes sense

Not sure why SPI behaves differently from I2C.

[Datasheet](https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FMS5611-01BA03%7FB3%7Fpdf%7FEnglish%7FENG_DS_MS5611-01BA03_B3.pdf%7FCAT-BLPS0036)

**Comment by RobTillaart** [comment]
Think the nano also has a 3v3 power output. You could try to power the sensor from that. Maybe use it too for the select pin.

**Comment by nachocpol** [comment]
True, although the signal wires are 5V, no way to change that. Had a quick go at porting this to the ESP32 WROOM 32 module now. SPI readings are correct, don't go up over time. Again, the ESP32 is 3V3.

**Comment by RobTillaart** [comment]
The voltage for the clock and data out can be reduced by a voltage divider. Might do the trick for the nano.

Good to hear the ESP worked.
